"""
Pydantic schemas for API requests/responses.
"""
from app.schemas.common import PaginationParams, PaginatedResponse, DateRangeParams
from app.schemas.kpi import KPICurrentResponse, KPIHistoryResponse, KPICompareResponse
from app.schemas.sales import (
    SalesSummaryResponse,
    SalesTrendsResponse,
    TopProductsResponse,
    SalesRegionsResponse,
)
from app.schemas.orders import (
    OrderStatusSummaryResponse,
    OrderListResponse,
    OrderDetailResponse,
    PlanExecutionLineItem,
    PlanExecutionResponse,
    DowntimeLineItem,
    DowntimeResponse,
)
from app.schemas.quality import (
    QualitySummaryResponse,
    DefectTrendsResponse,
    QualityLotsResponse,
    LotDeviationItem,
    LotDeviationsResponse,
)
from app.schemas.sync import SyncStatusResponse, SyncTriggerResponse
from app.schemas.personnel import (
    LocationResponse,
    ProductionLineResponse,
    DepartmentResponse,
    PositionResponse,
    WorkstationResponse,
    EmployeeResponse,
    PersonnelSummaryResponse,
)
from app.schemas.line_master_dashboard import (
    ShiftProgressResponse,
    ShiftComparisonResponse,
    DefectSummaryResponse,
)
from app.schemas.gm_dashboard import (
    OEEDataPoint,
    OEELineItem,
    OEESummaryResponse,
    PlanExecutionLineItem,
    PlanExecutionResponse,
    DowntimeLineItem,
    DowntimeRankingResponse,
)
from app.schemas.qe_dashboard import (
    TrendDataPoint,
    ParameterTrendItem,
    ParameterTrendsResponse,
    DeviationItem,
    BatchAnalysisItem,
    BatchAnalysisResponse,
    ParetoItem,
    DefectParetoResponse,
)
from app.schemas.finance_dashboard import (
    GroupByType,
    IntervalType,
    SortBy,
    SalesGroupItem,
    SalesBreakdownResponse,
    RevenueTrendPoint,
    RevenueTrendResponse,
    TopProductItem,
    TopProductsResponse as FinanceTopProductsResponse,
)
from app.schemas.analytics import (
    BatchInputCreate,
    BatchInputResponse,
    BatchInputListResponse,
    YieldResponse,
    DowntimeEventCreate,
    DowntimeEventResponse,
    DowntimeEventListResponse,
    DowntimeSummaryResponse,
    PromoCampaignCreate,
    PromoCampaignResponse,
    PromoCampaignListResponse,
    PromoCampaignEffectivenessResponse,
    KPIResponse,
    OTIFResponse,
    KPIBreakdownResponse,
    SalesMarginResponse,
    ProductionLinesListResponse,
    LineProductivityResponse,
    ScrapPercentageResponse,
    MarginalityResponse,
    CostPerKgResponse,
    EBITDAResponse,
    MarketShareResponse,
    CostBaseCreate,
    CostBaseResponse,
    CostBaseListResponse,
    KPIConfigCreate,
    KPIConfigResponse,
)
from app.schemas.oee import (
    OEEComponentResponse,
    OEELineResponse,
    OEESummaryResponse as OEECalculationSummaryResponse,
    LineCapacityPlanRequest,
    LineCapacityPlanResponse,
)

__all__ = [
    # Common
    "PaginationParams",
    "PaginatedResponse",
    "DateRangeParams",
    # KPI
    "KPICurrentResponse",
    "KPIHistoryResponse",
    "KPICompareResponse",
    # Sales
    "SalesSummaryResponse",
    "SalesTrendsResponse",
    "TopProductsResponse",
    "SalesRegionsResponse",
    # Orders
    "OrderStatusSummaryResponse",
    "OrderListResponse",
    "OrderDetailResponse",
    "PlanExecutionLineItem",
    "PlanExecutionResponse",
    "DowntimeLineItem",
    "DowntimeResponse",
    # Quality
    "QualitySummaryResponse",
    "DefectTrendsResponse",
    "QualityLotsResponse",
    "LotDeviationItem",
    "LotDeviationsResponse",
    # Sync
    "SyncStatusResponse",
    "SyncTriggerResponse",
    # Personnel
    "LocationResponse",
    "ProductionLineResponse",
    "DepartmentResponse",
    "PositionResponse",
    "WorkstationResponse",
    "EmployeeResponse",
    "PersonnelSummaryResponse",
    # Line Master Dashboard
    "ShiftProgressResponse",
    "ShiftComparisonResponse",
    "DefectSummaryResponse",
    # Group Manager Dashboard
    "OEEDataPoint",
    "OEELineItem",
    "OEESummaryResponse",
    "PlanExecutionLineItem",
    "PlanExecutionResponse",
    "DowntimeLineItem",
    "DowntimeRankingResponse",
    # Quality Engineer Dashboard
    "TrendDataPoint",
    "ParameterTrendItem",
    "ParameterTrendsResponse",
    "DeviationItem",
    "BatchAnalysisItem",
    "BatchAnalysisResponse",
    "ParetoItem",
    "DefectParetoResponse",
    # Finance Manager Dashboard
    "GroupByType",
    "IntervalType",
    "SortBy",
    "SalesGroupItem",
    "SalesBreakdownResponse",
    "RevenueTrendPoint",
    "RevenueTrendResponse",
    "TopProductItem",
    "FinanceTopProductsResponse",
    # Analytics
    "BatchInputCreate",
    "BatchInputResponse",
    "BatchInputListResponse",
    "YieldResponse",
    "DowntimeEventCreate",
    "DowntimeEventResponse",
    "DowntimeEventListResponse",
    "DowntimeSummaryResponse",
    "PromoCampaignCreate",
    "PromoCampaignResponse",
    "PromoCampaignListResponse",
    "PromoCampaignEffectivenessResponse",
    "KPIResponse",
    "OTIFResponse",
    "KPIBreakdownResponse",
    "SalesMarginResponse",
    "ProductionLinesListResponse",
    "LineProductivityResponse",
    "ScrapPercentageResponse",
    "MarginalityResponse",
    "CostPerKgResponse",
    "EBITDAResponse",
    "MarketShareResponse",
    "CostBaseCreate",
    "CostBaseResponse",
    "CostBaseListResponse",
    "KPIConfigCreate",
    "KPIConfigResponse",
    # OEE
    "OEEComponentResponse",
    "OEELineResponse",
    "OEECalculationSummaryResponse",
    "LineCapacityPlanRequest",
    "LineCapacityPlanResponse",
]
