"""add_products_output_sensors_inventory_sale_records

Revision ID: 1084a7ccef58
Revises: 7e28e392b990
Create Date: 2026-05-05 10:33:41.287873+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1084a7ccef58'
down_revision = '7e28e392b990'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_snapshots',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=3), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_date_warehouse', 'inventory_snapshots', ['snapshot_date', 'warehouse_code'], unique=False)
    op.create_index('idx_inventory_product_warehouse', 'inventory_snapshots', ['product_id', 'warehouse_code'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_product_id'), 'inventory_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_snapshot_date'), 'inventory_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_warehouse_code'), 'inventory_snapshots', ['warehouse_code'], unique=False)
    op.create_table('production_output',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=3), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_output_date_shift', 'production_output', ['production_date', 'shift'], unique=False)
    op.create_index('idx_output_product_date', 'production_output', ['product_id', 'production_date'], unique=False)
    op.create_index(op.f('ix_production_output_lot_number'), 'production_output', ['lot_number'], unique=False)
    op.create_index(op.f('ix_production_output_order_id'), 'production_output', ['order_id'], unique=False)
    op.create_index(op.f('ix_production_output_product_id'), 'production_output', ['product_id'], unique=False)
    op.create_index(op.f('ix_production_output_production_date'), 'production_output', ['production_date'], unique=False)
    op.create_index(op.f('ix_production_output_shift'), 'production_output', ['shift'], unique=False)
    op.create_index(op.f('ix_production_output_snapshot_date'), 'production_output', ['snapshot_date'], unique=False)
    op.create_table('products',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('requires_quality_check', sa.Boolean(), nullable=True),
    sa.Column('source_system_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_category_brand', 'products', ['category', 'brand'], unique=False)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_table('sale_records',
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=3), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_records_channel_date', 'sale_records', ['channel', 'sale_date'], unique=False)
    op.create_index('idx_sale_records_product_date', 'sale_records', ['product_id', 'sale_date'], unique=False)
    op.create_index(op.f('ix_sale_records_channel'), 'sale_records', ['channel'], unique=False)
    op.create_index(op.f('ix_sale_records_external_id'), 'sale_records', ['external_id'], unique=False)
    op.create_index(op.f('ix_sale_records_product_id'), 'sale_records', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_records_region'), 'sale_records', ['region'], unique=False)
    op.create_index(op.f('ix_sale_records_sale_date'), 'sale_records', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sale_records_snapshot_date'), 'sale_records', ['snapshot_date'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('production_line', sa.String(length=50), nullable=False),
    sa.Column('parameter_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensor_line_date', 'sensor_readings', ['production_line', 'recorded_at'], unique=False)
    op.create_index('idx_sensor_line_param', 'sensor_readings', ['production_line', 'parameter_name'], unique=False)
    op.create_index(op.f('ix_sensor_readings_device_id'), 'sensor_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_parameter_name'), 'sensor_readings', ['parameter_name'], unique=False)
    op.create_index(op.f('ix_sensor_readings_production_line'), 'sensor_readings', ['production_line'], unique=False)
    op.create_index(op.f('ix_sensor_readings_quality'), 'sensor_readings', ['quality'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_snapshot_date'), 'sensor_readings', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_snapshot_date'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_quality'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_production_line'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_parameter_name'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_device_id'), table_name='sensor_readings')
    op.drop_index('idx_sensor_line_param', table_name='sensor_readings')
    op.drop_index('idx_sensor_line_date', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_sale_records_snapshot_date'), table_name='sale_records')
    op.drop_index(op.f('ix_sale_records_sale_date'), table_name='sale_records')
    op.drop_index(op.f('ix_sale_records_region'), table_name='sale_records')
    op.drop_index(op.f('ix_sale_records_product_id'), table_name='sale_records')
    op.drop_index(op.f('ix_sale_records_external_id'), table_name='sale_records')
    op.drop_index(op.f('ix_sale_records_channel'), table_name='sale_records')
    op.drop_index('idx_sale_records_product_date', table_name='sale_records')
    op.drop_index('idx_sale_records_channel_date', table_name='sale_records')
    op.drop_table('sale_records')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index('idx_products_category_brand', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_production_output_snapshot_date'), table_name='production_output')
    op.drop_index(op.f('ix_production_output_shift'), table_name='production_output')
    op.drop_index(op.f('ix_production_output_production_date'), table_name='production_output')
    op.drop_index(op.f('ix_production_output_product_id'), table_name='production_output')
    op.drop_index(op.f('ix_production_output_order_id'), table_name='production_output')
    op.drop_index(op.f('ix_production_output_lot_number'), table_name='production_output')
    op.drop_index('idx_output_product_date', table_name='production_output')
    op.drop_index('idx_output_date_shift', table_name='production_output')
    op.drop_table('production_output')
    op.drop_index(op.f('ix_inventory_snapshots_warehouse_code'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_snapshot_date'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_product_id'), table_name='inventory_snapshots')
    op.drop_index('idx_inventory_product_warehouse', table_name='inventory_snapshots')
    op.drop_index('idx_inventory_date_warehouse', table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    # ### end Alembic commands ###
