"""create dashboard tables

Revision ID: 7e28e392b990
Revises: 
Create Date: 2026-04-27 17:50:31.053194+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e28e392b990'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_kpi',
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('production_line', sa.String(length=50), nullable=True),
    sa.Column('total_output', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('defect_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('completed_orders', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('oee_estimate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('avg_order_completion_time', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_from', 'period_to', 'production_line', name='uix_kpi_period_line')
    )
    op.create_index(op.f('ix_aggregated_kpi_period_from'), 'aggregated_kpi', ['period_from'], unique=False)
    op.create_index(op.f('ix_aggregated_kpi_period_to'), 'aggregated_kpi', ['period_to'], unique=False)
    op.create_index(op.f('ix_aggregated_kpi_production_line'), 'aggregated_kpi', ['production_line'], unique=False)
    op.create_table('aggregated_sales',
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('group_by_type', sa.String(length=20), nullable=False),
    sa.Column('group_key', sa.String(length=100), nullable=False),
    sa.Column('total_quantity', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('sales_count', sa.Integer(), nullable=False),
    sa.Column('avg_order_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_from', 'period_to', 'group_by_type', 'group_key', name='uix_sales_period_group')
    )
    op.create_index('idx_sales_group_type', 'aggregated_sales', ['group_by_type'], unique=False)
    op.create_index('idx_sales_period', 'aggregated_sales', ['period_from', 'period_to'], unique=False)
    op.create_table('order_snapshots',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('external_order_id', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('target_quantity', sa.DECIMAL(precision=15, scale=3), nullable=True),
    sa.Column('actual_quantity', sa.DECIMAL(precision=15, scale=3), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('production_line', sa.String(length=50), nullable=True),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_snapshots_composite', 'order_snapshots', ['snapshot_date', 'status', 'production_line'], unique=False)
    op.create_index(op.f('ix_order_snapshots_order_id'), 'order_snapshots', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_snapshots_production_line'), 'order_snapshots', ['production_line'], unique=False)
    op.create_index(op.f('ix_order_snapshots_snapshot_date'), 'order_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_order_snapshots_status'), 'order_snapshots', ['status'], unique=False)
    op.create_table('quality_results',
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('parameter_name', sa.String(length=50), nullable=False),
    sa.Column('result_value', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('lower_limit', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('upper_limit', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('in_spec', sa.Boolean(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quality_date_decision', 'quality_results', ['test_date', 'decision'], unique=False)
    op.create_index('idx_quality_product_date', 'quality_results', ['product_id', 'test_date'], unique=False)
    op.create_index(op.f('ix_quality_results_decision'), 'quality_results', ['decision'], unique=False)
    op.create_index(op.f('ix_quality_results_lot_number'), 'quality_results', ['lot_number'], unique=False)
    op.create_index(op.f('ix_quality_results_product_id'), 'quality_results', ['product_id'], unique=False)
    op.create_index(op.f('ix_quality_results_test_date'), 'quality_results', ['test_date'], unique=False)
    op.create_table('sales_trends',
    sa.Column('trend_date', sa.Date(), nullable=False),
    sa.Column('interval_type', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_quantity', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trend_date', 'interval_type', 'region', 'channel', name='uix_trends_date_interval')
    )
    op.create_index('idx_trends_date', 'sales_trends', ['trend_date'], unique=False)
    op.create_index('idx_trends_interval', 'sales_trends', ['interval_type'], unique=False)
    op.create_table('sync_logs',
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_started', 'sync_logs', ['started_at'], unique=False)
    op.create_index('idx_sync_task_status', 'sync_logs', ['task_name', 'status'], unique=False)
    op.create_index(op.f('ix_sync_logs_status'), 'sync_logs', ['status'], unique=False)
    op.create_index(op.f('ix_sync_logs_task_name'), 'sync_logs', ['task_name'], unique=False)
    op.create_table('sync_errors',
    sa.Column('sync_log_id', sa.UUID(), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sync_log_id'], ['sync_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_sync_log', 'sync_errors', ['sync_log_id'], unique=False)
    op.create_index('idx_error_type', 'sync_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_sync_errors_error_type'), 'sync_errors', ['error_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_errors_error_type'), table_name='sync_errors')
    op.drop_index('idx_error_type', table_name='sync_errors')
    op.drop_index('idx_error_sync_log', table_name='sync_errors')
    op.drop_table('sync_errors')
    op.drop_index(op.f('ix_sync_logs_task_name'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_status'), table_name='sync_logs')
    op.drop_index('idx_sync_task_status', table_name='sync_logs')
    op.drop_index('idx_sync_started', table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index('idx_trends_interval', table_name='sales_trends')
    op.drop_index('idx_trends_date', table_name='sales_trends')
    op.drop_table('sales_trends')
    op.drop_index(op.f('ix_quality_results_test_date'), table_name='quality_results')
    op.drop_index(op.f('ix_quality_results_product_id'), table_name='quality_results')
    op.drop_index(op.f('ix_quality_results_lot_number'), table_name='quality_results')
    op.drop_index(op.f('ix_quality_results_decision'), table_name='quality_results')
    op.drop_index('idx_quality_product_date', table_name='quality_results')
    op.drop_index('idx_quality_date_decision', table_name='quality_results')
    op.drop_table('quality_results')
    op.drop_index(op.f('ix_order_snapshots_status'), table_name='order_snapshots')
    op.drop_index(op.f('ix_order_snapshots_snapshot_date'), table_name='order_snapshots')
    op.drop_index(op.f('ix_order_snapshots_production_line'), table_name='order_snapshots')
    op.drop_index(op.f('ix_order_snapshots_order_id'), table_name='order_snapshots')
    op.drop_index('idx_order_snapshots_composite', table_name='order_snapshots')
    op.drop_table('order_snapshots')
    op.drop_index('idx_sales_period', table_name='aggregated_sales')
    op.drop_index('idx_sales_group_type', table_name='aggregated_sales')
    op.drop_table('aggregated_sales')
    op.drop_index(op.f('ix_aggregated_kpi_production_line'), table_name='aggregated_kpi')
    op.drop_index(op.f('ix_aggregated_kpi_period_to'), table_name='aggregated_kpi')
    op.drop_index(op.f('ix_aggregated_kpi_period_from'), table_name='aggregated_kpi')
    op.drop_table('aggregated_kpi')
    # ### end Alembic commands ###
